Repository travis-ci/docs-travis-ci-com, pull requests merged in 2018-11, with the labels that each got.

#2098 Explain how setup worker behind a proxy
  user/enterprise/upgrading.md
  user/enterprise/worker-configuration.md
Labels: enterprise

#2013 Concurrency insights on enterprise
  user/enterprise.md
  user/enterprise/platform-tips.md
Labels: enterprise

#1665 Testfairy remove instrumentation, simplified testfairy provider, no need of keystore file
  user/deployment/testfairy.md
Labels: dpl

#2078 Document cargo deploy provider
  _data/deployments.yml
  user/deployment/cargo.md
Labels: dpl

#1679 Added new option from travis-ci/dpl#677
  user/deployment/pages.md
Labels: dpl

#2095 Single Linux prep work
  .travis.yml
  user/build-stages/share-docker-image.md
  user/chrome.md
  user/common-build-problems.md
  user/database-setup.md
  user/docker.md
  user/for-beginners.md
  user/hostname.md
  user/installing-dependencies.md
  user/integration/platformio.md
  user/ip-addresses.md
  user/languages/java.md
  user/languages/javascript-with-nodejs.md
  user/languages/minimal-and-generic.md
  user/languages/r.md
  user/languages/smalltalk.md
  user/migrating-from-legacy.md
  user/multi-os.md
  user/reference/git
  user/reference/overview.md
  user/reference/precise.md
  user/reference/trusty.md
  user/tutorial.md
Labels: WIP

#2125 Add install guide for Xenial build env
  _data/enterprise.yml
  user/enterprise/trusty.md
  user/enterprise/xenial.md
Labels: enterprise
