Repository travis-ci/docs-travis-ci-com, pull requests merged in 2018-05, with the labels that each got.

#1675 [Enterprise] Move ops manual "contact support" to snippets
  _data/enterprise.yml
  _data/snippets.yml
  user/enterprise.md
  user/enterprise/operations-manual.md
Labels: enterprise

#1813 fix path to assets when visiting /api
  config.rb
Labels: in progress

#1818 Migrate repo to GitHub apps guide
  images/github-app-page.png
  images/github-app-repo.png
  images/legacy-services-repo.png
  user/legacy-services-to-github-apps-migration-guide.md
Labels: in progress

#1811 Some prep for the future
  _includes/sidebar.html
  slate/source/index.md
  user/apps.md
  user/best-practices-security.md
  user/build-feeds.md
  user/caching.md
  user/customizing-the-build.md
  user/deployment/pages.md
  user/developer.md
  user/encrypting-files.md
  user/enterprise/build-images.md
  user/for-beginners.md
  user/getting-started.md
  user/github-oauth-scopes.md
  user/gui-and-headless-browsers.md
  user/languages/c.md
  user/languages/clojure.md
  user/languages/cpp.md
  user/languages/dart.md
  user/languages/erlang.md
  user/languages/haxe.md
  user/languages/julia.md
  user/languages/perl.md
  user/languages/perl6.md
  user/languages/ruby.md
  user/notifications.md
  user/open-source-on-travis-ci-com.md
  user/private-dependencies.md
  user/reference/precise.md
  user/repository-providers.md
  user/running-build-in-debug-mode.md
  user/speeding-up-the-build.md
  user/triggering-builds.md
Labels: in progress

#1829 travis_migrate_to_apps gem guide
  user/travis-migrate-to-apps-gem-guide.md
Labels: in progress

#1814 Update prerequisites deprecated.md
  user/enterprise/prerequisites.md
Labels: in progress

#1803 Update Enterprise docs for the public Xenial Beta
  _data/enterprise.yml
  user/enterprise/build-images.md
  user/enterprise/install-on-xenial.md
  user/enterprise/installation.md
  user/enterprise/operations-manual.md
  user/enterprise/platform-tips.md
  user/enterprise/precise.md
  user/enterprise/trusty-build-containers.md
  user/enterprise/worker-cli-commands.md
  user/enterprise/worker-configuration.md
Labels: enterprise, in progress

#1850 Add/Update legal section for gdpr
  _includes/sidebar.html
  legal/data-processing-agreement.md
  legal/privacy-policy.md
  legal/terms-conditions.md
  legal/terms-of-service.md
Labels: Do Not Merge

#1852 Update footer
  _includes/footer.html
  assets/javascripts/main.js
  assets/stylesheets/_footer.sass
Labels: in progress

#1862 Fix Ubuntu OS version requirement
  user/enterprise/prerequisites.md
Labels: enterprise

#1863 Clarifywhere you can use travis_retry
  user/common-build-problems.md
Labels: in progress
