Repository travis-ci/docs-travis-ci-com, pull requests merged in 2018-04, with the labels that each got.

#1788 Update FTP (un)usage recommendations
  user/common-build-problems.md
  user/deployment/custom.md
Labels: awaiting-review

#1780 Explain that services: docker only works on hosted
  user/docker.md
  user/enterprise/build-images.md
Labels: enterprise

#1790 Link to PR builds
  user/customizing-the-build.md
Labels: in progress

#1791 add "I pushed a commit and can't find its corresponding build" to Common Build Problems
  images/common-build-problems/repository-requests-page.png
  user/common-build-problems.md
Labels: in progress

#1794 Updated to Xcode 9.3 GA
  _data/xcodes.yml
  user/build-environment-updates/2018-04-09.md
Labels: in progress

#1796 Define IP address range for all "linux containers"
  Rakefile
  user/ip-addresses.md
Labels: awaiting-review, in progress

#1798 Add workaround for RHS fns
  user/conditional-builds-stages-jobs.md
Labels: in progress

#1804 Document set e
  user/common-build-problems.md
  user/customizing-the-build.md
Labels: in progress

#1805 Remove references to specific storage vendors
  user/caching.md
Labels: in progress

#1808 Add notice about adding a delay before running commands
  Rakefile
  user/deployment/heroku.md
Labels: in progress

#1806 add 'travis-worker is not starting' case to ops manual
  user/enterprise/operations-manual.md
Labels: enterprise, in progress
