Repository travis-ci/docs-travis-ci-com, pull requests merged in 2019-11, with the labels that each got.

#2286 Enumerate valid GitHub Releases options
  user/deployment/releases.md
Labels: dpl

#2365 Config imports
  _includes/sidebar.html
  user/build-config-imports.md
Labels: Do Not Merge, in progress

#2583 Multi CPU Arch - add IBM Power and Z support
  user/multi-cpu-architectures.md
Labels: Do Not Merge

#2584 Adding info on IBM Power and Z support
  user/reference/overview.md
Labels: Do Not Merge
